name: Build and Push to Private Registry

on:
  push:
    branches: ['master']
  pull_request:
    branches: ['master']

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      # Repository auschecken
      - name: Check out repository
        uses: actions/checkout@v4

      # Docker-Login mit Umgebungsvariablen (non-interaktiv)
      - name: Log in to Docker Registry
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
          DOCKER_REGISTRY: ${{ secrets.DOCKER_REGISTRY }}
        run: |
          echo "$DOCKER_PASSWORD" | docker login "$DOCKER_REGISTRY" -u "$DOCKER_USERNAME" --password-stdin

      # Docker-Image bauen
      - name: Build Docker Image
        env:
          DOCKER_REGISTRY: ${{ secrets.DOCKER_REGISTRY }}
        run: |
          docker build -t $DOCKER_REGISTRY/innenanzeiger:latest .

      # Docker-Image pushen
      - name: Push Docker Image
        env:
          DOCKER_REGISTRY: ${{ secrets.DOCKER_REGISTRY }}
        run: |
          docker push $DOCKER_REGISTRY/innenanzeiger:latest
